### ISSUE TITLE
New gps fix is not requested when MovingStart event occurs

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_avl_tests#2]
MovingStart event should request the new gps fix but it does not.

Steps to reproduce:
1. Set gpsReadInterval (in postiion service) for 30 seconds;
2. Set movingDebounceTime to 15 seconds and stationarySpeedThld to 5 kmh; 
2. Increase speed one kmh above stationarySpeedThld 
3. Wait for time longer than movingDebounceTime, then check if the MovingStart message has been sent.
4. Check the value of the GpsFixAge in the report - that is 15 which is incorrect (no new fix requested by the event)

Version of AVL Agent: v3.2.2 r1625

**Comment by afarran** [comment]
Because the fix is not considered stale in that case (i.e. not too old) so there's no need to request and wait for another one.
