### ISSUE TITLE
Digital input line 13 does not affect SeatbeltOff state

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_avl_tests#26]
Line number 13 is a special virtual digital input that indicates whether the terminal is powered by an external source. By setting property FuncDigInp13 (PIN 59) this line may be associated like other digital input lines with functions like: IgnitionOn, SeatbeltOff, SM1 Active and so on. 
**For setting FuncDigInp13 = 3 (Seatbelt) this line does not change SeatbeltOff state at all.** 
Neither when switching from high to low nor when switching from low to high. 

**Steps to reproduce:**
1. Set FuncDigInp13 (PIN 59) to value 3 (that is for Seatbelt function)
2. Set DigStatesDefBitmap (PIN 46) to value 2
3. Simulate external power source not present (line 13 changes state to 0) 
4. Seatbelt event is not generated.
5. Simulate external power source present (line changes state to 1)
6. Seatbelt event is not generated.

Version of AVL service: v3.2.2 r1625

**Comment by TroyManary** [comment]
Argus 21641

**Comment by afarran** [comment]
Configuration change to I/O properties take effect after a terminal restart. In v3.4.0 such changes will take effect immediately.
