### ISSUE TITLE
Speeding: defaultSpeedLimit set to 0 does not disable speeding feature

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_avl_tests#3]
According to specification PIN5 - DefaultSpeedLimit: "Default speed limit used to determine if amoving vehicle is speeding (0 = feature disabled). Measured in km/h" (005 AS027 AVL Agent User Guide) 
But setting it 0 does not disable speeding feature and reports are generated for any speed above 0 kmh. 

Steps to reproduce:
1. Set gpsReadInterval (continues mode in position service) to 1 (gps read every second)
2. Set defaultSpeedLimit = 0, speedingTimeOver = 1, movingDebounceTime = 1, stationarySpeedThld = 2  
3. Simulate speed of 3 kmh and wait longer than one second.
4. After that two event appears: MovingStart (which is correct) and SpeedingStart (which is not correct); in the SpeedingStart message the reported speed is 3 kmh      

Expected behaviour: Setting defaultSpeedLimit = 0 should disable speeding feature (no SpeedingStart message sent)

Version of AVL Agent: v3.2.2 r1625

Related TC: test_Speeding_WhenSpeedAboveSpeedingThldForPeriodAboveThldForSpeedingFeatureDisabled_SpeedingStartMessageNotSent

**Comment by afarran** [comment]
Fixed in v3.4.0
