### ISSUE TITLE
DigitalOutputs: when LPM trigger is set to BuiltInBattery and external power source is present digital output associated with LPM trigger line does not go back to low state

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_avl_tests#35]
The digital output line associated with LPM trigger does not go back to low state when external power source is present again. 

Steps to reproduce:
  0. Set SIN=17(power) PIN=5(extPowerPresentStateDetect) to value "Both"
  1. Configure port 1 as a digital output and associate this port with LowPower function
  2. Set the high state of the output be the indicator of active line
  3. Set lpmEntryDelay (PIN 32) to high value (terminal is not supposed to enter low power mode)
  4. Set lpmTrigger (PIN 31) to Built-on battery
  5. Simulate external power source present
  6. Check the state of digital output port - line in low state
  7. Simulate external power source not present
  8. Ckeck the state of digital output port - line is in high state - that is correct
  9. Simulate external power source present again
  10. Check the state of digital output port - it does not go to low state

version of AVL: 3.2.2

**Comment by afarran** [comment]
Can't reproduce
