### ISSUE TITLE
DriverId Features - deleting more than 100 gives strange error message.

### ISSUE THREAD

**Issue by pblo** [afarran/swm2m_avl_tests#45]
DriverId Features - deleting more than 100 gives strange or just non-descriptive error message.

Output : "Terminal couldn't process msg."
SIN = 18
Payload.Name = "msgError"
Payload.MIN = 4
Error description is : "Set driver ID error: data/svc/AVL/DriverId.dat: no such file or directory"

Not necessarily bug, rather question.

**Comment by TroyManary** [comment]
Argus 21642

**Comment by afarran** [comment]
Can't reproduce. Where are the steps to reproduce? The SetDriverIds --> DeleteIds message field is an array that has a maximum size of 100. How did you send more than 100 IDs?
