### ISSUE TITLE
IgnitionON (and other I/O related events) are generated immediately after line state is changed

### ISSUE THREAD

**Issue by ArturMalyszewicz** [afarran/swm2m_avl_tests#6]
Description of IgnitionON event in AS027 is this:
“When the Ignition line changes (DigStatesDefBitmap) for at least 3 seconds or as per line configurations in the EEIO or EIO core service”
But for default settings no 3 seconds delay is observed and event is generated immediately after assiociated port state is changed. Also changing value of the port1EdgeSampleCount does not influence delay after which the event appears

Steps to reproduce:
1. configure port 1 as a digital input (port1Config = 3) 
2. associate this port with IgnitionOn line  -- (funcDigInp1 = 2)
3. I set the high state of the port to be a trigger for line activation  (digStatesDefBitmap = 3)
4. simulate port 1 value change to high state and wait for IgnitionOn message
5. Observe the time difference between port state change and IgnitionOn message.

Version of AVL Agent: v3.2.2 r1625

**Comment by afarran** [comment]
Documentation updated
